### ISSUE TITLE
Personnal Lookup non fonctionnel

### ISSUE THREAD

**Issue by samixchoumi** [lulz3xploit/LittleBrother#31]
Salut,

Je voulais tester ce petit programme et en lançant une recherche sur moi même j'ai la stack suivante qui s'affiche : 
```
Traceback (most recent call last):
  File "LittleBrother.py", line 199, in <module>
    searchPersonne(settings.codemonpays)
  File "C:\LittleBrother\core\searchPersonne.py", line 43, in searchPersonne
    searchPJ(requete)
  File "C:\LittleBrother\core\searchPJ.py", line 47, in searchPJ
    print("\n"+table_instance.table)
  File "C:\Python\Python38\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Python\Python38\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Python\Python38\site-packages\colorama\ansitowin32.py", line 190, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "C:\Python\Python38\site-packages\colorama\ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
  File "C:\Python\Python38\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Python\Python38\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Python\Python38\site-packages\colorama\ansitowin32.py", line 190, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "C:\Python\Python38\site-packages\colorama\ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
  File "C:\Python\Python38\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Python\Python38\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Python\Python38\site-packages\colorama\ansitowin32.py", line 190, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "C:\Python\Python38\site-packages\colorama\ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
  File "C:\Python\Python38\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Python\Python38\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Python\Python38\site-packages\colorama\ansitowin32.py", line 190, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "C:\Python\Python38\site-packages\colorama\ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
  File "C:\Python\Python38\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Python\Python38\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Python\Python38\site-packages\colorama\ansitowin32.py", line 190, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "C:\Python\Python38\site-packages\colorama\ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
  File "C:\Python\Python38\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Python\Python38\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Python\Python38\site-packages\colorama\ansitowin32.py", line 190, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "C:\Python\Python38\site-packages\colorama\ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
  File "C:\Python\Python38\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Python\Python38\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Python\Python38\site-packages\colorama\ansitowin32.py", line 190, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "C:\Python\Python38\site-packages\colorama\ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
  File "C:\Python\Python38-32\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u250c' in position 2: character maps to <undefined>
```
Une idée du pourquoi ?

**Comment by lrhel** [comment]
Je pense que c'est relatif a l'encodage chez Windows, enfin de mon cote je n'arrive pas a reproduire le bug.
Donc je vais laisser @lulz3xploit s'en occuper.

**Comment by lulz3xploit** [comment]
Bonjour, se genre de problème arrive souvent sous Windows. Généralement il arrive quand on utilise la version 2 de python. Mais vu que python essaye d’aller dans le répertoire de python38.. je pense pas que ça vient de ça. 
Il est possible aussi qu’un résultat trouvé (pseudo ou autre) comporte un code ascii pas pris en compte par Windows. J’ai du mal encoder le résultat dans le code.

Essayez de faire ceci: 
Dans `LittleBrother/core/searchPJ.py` à la ligne `19` il y’a un commentaire:  `# content.decode(« utf-8 »)`
Modifier le code `page = requete.text`
Par `page = requete.content.decode(« utf-8 »)` *(le commentaire à côté)* 

Essayez de lancer la recherche. Si aucun problème ne survient. C’est que le problème venait de la. Faites le moi savoir pour que je le corrige. Merci

**Comment by samixchoumi** [comment]
Bonjour,
Je viens de modifier la ligne comme évoqué, le problème persiste toujours.

**Comment by lulz3xploit** [comment]
Le problème vient de Windows alors..
