### ISSUE TITLE
IndexError pb

### ISSUE THREAD

**Issue by iamtend0** [lulz3xploit/LittleBrother#33]
```
Traceback (most recent call last):
  File "LittleBrother.py", line 221, in <module>
    searchTwitter()
  File "/home/kali/LittleBrother/core/searchTwitter.py", line 6, in searchTwitter
    twitool.getInfoProfile(username)
  File "/home/kali/LittleBrother/core/twitterSearchTool.py", line 55, in getInfoProfile
    data =  jsonData[0].replace("&quot;", "\"")
```

Salut,

Petit soucis quand j'utilise lookup twitter 
J'ai aussi une erreur IndexError quand j'utilise le profiler

**Comment by lulz3xploit** [comment]
@t3nd0 Bonjour, puis-je avoir l’erreur complète, et, si possible, les arguments que vous avez utilisé pour avoir cette erreur ?

**Comment by 0xTheOldOne** [comment]
Bonsoir, j'ai exactement la même erreur quand j'utilise le lookup twitter sur Windows et ce, avec n'importe quel @ : 

> python3 ./LittleBrother.py
[...]
> LittleBrother(Lookup)$ 12
> Username: ourobourrin

```
Traceback (most recent call last):
  File "./LittleBrother.py", line 221, in <module>
    searchTwitter()
  File "E:\Tools\LittleBrother-master\core\searchTwitter.py", line 6, in searchTwitter
    twitool.getInfoProfile(username)
  File "E:\Tools\LittleBrother-master\core\twitterSearchTool.py", line 55, in getInfoProfile
    data =  jsonData[0].replace("&quot;", "\"")
IndexError: list index out of range
```

Dans `twitterSearchTool`, ligne 55,  `jsonData` est null, la regex de la ligne précédente ne match pas alors que `page` a bien une valeur : 
> re.findall(r"<input type=\"hidden\" id=\"init-data\" class=\"json-data\" value=\"(.*)\">", page)

Via [regex101.com](https://regex101.com/) avec Python en flavor : 

![image](https://user-images.githubusercontent.com/60443792/86653735-b39c4380-bfe5-11ea-8490-02b2ba968f2e.png)

À première vue j'aurais dit qu'il n'y a plus de balise `<input />` dans le retour d'un GET sur `"https://twitter.com/"+username` mais c'est qu'en fait on tombe sur la page qui nous indique que le code JS n'a pas été exécuté (la balise `<noscript>`) et nous demande si on veut utiliser _l'ancien_ twitter, ici avec un screen du GET sur mon @ twitter via PostMan : 

![image](https://user-images.githubusercontent.com/60443792/86658943-bdc04100-bfe9-11ea-9a4f-97dfe6cd9d80.png)

🤔 Potentiellement il y a une solution avec ce module qui permet d'exécuter du JS (au render de la page) : 

- [https://stackoverflow.com/a/54056631/2003597](https://stackoverflow.com/a/54056631/2003597)
- https://pypi.org/project/requests-html/

Je ne suis pas du tout à l'aise en python mais c'est tout ce que je peux dire pour aider...

**Comment by lulz3xploit** [comment]
@ourobourrin  Bonjour, oui effectivement, merci beaucoup pour vos recherche, ça m’aide beaucoup. J’essayerais de mettre ça à jour le plus rapidement possible

**Comment by iamtend0** [comment]
Bonjour, excusez-moi pour ma réponse tardive mais je n'ai plus accès à la machine ayant eu l'erreur. Désolé pour le remontage d'erreur sans logs ! Et merci à @ourobourrin pour l'apport d'infos

**Comment by lulz3xploit** [comment]
> Bonjour, excusez-moi pour ma réponse tardive mais je n'ai plus accès à la machine ayant eu l'erreur. Désolé pour le remontage d'erreur sans logs ! Et merci à @ourobourrin pour l'apport d'infos

Bonjour, Que voulez vous dire par "ne plus avoir accès à la machine ayant eu l'erreur" ?

**Comment by iamtend0** [comment]
> > Bonjour, excusez-moi pour ma réponse tardive mais je n'ai plus accès à la machine ayant eu l'erreur. Désolé pour le remontage d'erreur sans logs ! Et merci à @ourobourrin pour l'apport d'infos
> 
> Bonjour, Que voulez vous dire par "ne plus avoir accès à la machine ayant eu l'erreur" ?

Concernant la demande https://github.com/lulz3xploit/LittleBrother/issues/33#issuecomment-639036036
Je n'ai plus accès à la machine ayant soulevé l'erreur. Il me faut installer à nouveau l'outil et voir si les mêmes erreurs apparaissent sur une autre...

**Comment by lulz3xploit** [comment]
> > > Bonjour, excusez-moi pour ma réponse tardive mais je n'ai plus accès à la machine ayant eu l'erreur. Désolé pour le remontage d'erreur sans logs ! Et merci à @ourobourrin pour l'apport d'infos
> 
> > 
> 
> > Bonjour, Que voulez vous dire par "ne plus avoir accès à la machine ayant eu l'erreur" ?
> 
> 
> 
> Concernant la demande https://github.com/lulz3xploit/LittleBrother/issues/33#issuecomment-639036036
> 
> Je n'ai plus accès à la machine ayant soulevé l'erreur. Il me faut installer à nouveau l'outil et voir si les mêmes erreurs apparaissent sur une autre...

Ah d'accord. L'erreur sera toujours présente car je dois retravailler le code à cause d'une modification que Twitter ont fait sur leur site.

**Comment by 0xTheOldOne** [comment]
@lulz3xploit pourquoi la fermeture du ticket ? (je ne vois pas de corrections concernant ce point)

**Comment by lulz3xploit** [comment]
@ourobourrin Bonjour, c'était une erreur. Désolé
