### ISSUE TITLE
Module  13 instagram

### ISSUE THREAD

**Issue by SN4K3D** [lulz3xploit/LittleBrother#42]
username: blabla blabla
`Traceback (most recent call last):
  File "LittleBrother.py", line 223, in <module>
    searchInstagram()
  File "/home/snake/LittleBrother/core/searchInstagram.py", line 21, in searchInstagram
    images = shortCutUrl(images)`

L'outil ce ferme a la suite de ce problème

**Comment by lulz3xploit** [comment]
Bonjour, merci de votre retour, le problème a été corrigé.
