### ISSUE TITLE
Running error 

### ISSUE THREAD

**Issue by shamashan** [lulz3xploit/LittleBrother#47]
Hello, I am receiving this error when I start the tool.

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f78a3e05070>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 724, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='ip-api.com', port=80): Max retries exceeded with url: /json/195.47.194.37 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f78a3e05070>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "LittleBrother.py", line 32, in <module>
    settings.init()
  File "/root/LittleBrother/settings.py", line 34, in init
    monpays = requests.get("http://ip-api.com/json/"+monip).text
  File "/usr/lib/python3/dist-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='ip-api.com', port=80): Max retries exceeded with url: /json/195.47.194.37 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f78a3e05070>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by lulz3xploit** [comment]
@shamashan Hello, thank you for your return. I see where the mistake came from and I would correct it tomorrow

**Comment by lulz3xploit** [comment]
@shamashan Hello, when I wanted to correct the error I realized that everything works. There was probably a problem with the domain [ip-api.com](ip-api.com). Can you try to run LittleBrother and tell me if it works for you ?

**Comment by shamashan** [comment]
Thank you @lulz3xploit. Unfortunately, still have the same problem.

**Comment by lulz3xploit** [comment]
@shamashan Do you use a VPN?

**Comment by shamashan** [comment]
Yes, ı do

**Comment by lulz3xploit** [comment]
I think [ip-api.com](https://ip-api.com) doesn’t like VPNs. So you should disable your VPN in order to use LittleBrother (I specify that this was not wanted). I would correct this if I had time. Sorry for the inconvenience

**Comment by shamashan** [comment]
Thank you!

**Comment by ip-api** [comment]
> 
> 
> I think [ip-api.com](https://ip-api.com) doesn’t like VPNs. So you should disable your VPN in order to use LittleBrother (I specify that this was not wanted). I would correct this if I had time. Sorry for the inconvenience

Hi,

ip-api.com likes VPNs, the block is not on our side. Most likely the VPN provider hijacks the DNS request (ie Pi-hole) to ip-api.com and it resolves to a different IP, ie 127.0.0.1.

You can try adding this to your hosts file and see if it fixes it:

`208.95.112.1 ip-api.com`

**Comment by lulz3xploit** [comment]
Yes, because some vpn blocks this domain. In any case in the first version of littlebrother it was because of that, users who disconnect from their vpn no longer had any problem. But I don’t know if I was using another api or if it was always ip-api.com

I also noticed that after several requests, the api returns:`{"status":"fail","message":"SSL unavailable for this endpoint, order a key at https://members.ip-api.com/"}`

**Comment by ip-api** [comment]
> 
> 
> I also noticed that after several requests, the api returns:`{"status":"fail","message":"SSL unavailable for this endpoint, order a key at https://members.ip-api.com/"}`

The free API does not allow TLS/https, but you will get that error only if you're accessing the API via https. Perhaps you're getting redirected to the https version by a browser add-on.

**Comment by lulz3xploit** [comment]
Yes, So it’s good because of a vpn that blocks some dns, I only see that. All the people who encountered this error, are people who used a VPN.
