### ISSUE TITLE
Problème avec SMS

### ISSUE THREAD

**Issue by hacker66677** [lulz3xploit/LittleBrother#9]
Bonjour, lorsque j'utilise l'option SMS dans la partie social engineering, j'obtiens l'erreur suivante lorsque je rentre l'ID du server : 
Traceback (most recent call last):
  File "LittleBrother.py", line 2084, in <module>
    receive_sms()
  File "LittleBrother.py", line 1414, in receive_sms
    receive.sms(url)
  File "LittleBrother.py", line 175, in sms
    self.messageText = messagesList[1]
IndexError: list index out of range

**Comment by lulz3xploit** [comment]
Bonjour, désolé du retard, mais le module SMS a été retiré de LittleBrother, celui ci n’étant pas très intéressant
